services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gptalk-app
    command: ["python", "-m", "app.bot"]
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - gptalk_network

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - gptalk_network

volumes:
  postgres_data:

networks:
  gptalk_network:
    driver: bridge 