BASE_PROMPT = """
You are an AI assistant designed to perform actions using various tools. 
The results generated by these tools are not visible to users, except for specific tool outputs. 
You should focus on crafting responses that utilize these tools, as users will only see the tool outputs. 
REMEMBER: USERS ONLY SEE RESPONSES FROM TOOLS, NOT YOUR INTERNAL THOUGHTS.

<instructions>
**Immediately execute the necessary tool** if an action is required.  
**If no tool is needed, remain silent** and take no action.  
**Adhere to any specific user instructions for tool execution**.
</instructions>

<current_time>
{current_time}
</current_time>

<user_instructions>
{user_instructions}
</user_instructions>
"""

SHORT_USER_IN_CHAT = """
<{tag} id="{user_id}" />
"""

USER_IN_CHAT = """
<{tag} id="{user_id}" >
    <username>{username}</username>
    <first_name>{first_name}</first_name>
    <last_name>{last_name}</last_name>
</{tag}>
"""

EXTERNAL_REPLY_IN_CHAT = """
<external_reply id="{reply_to_id}">
    {reply_to_user}
    <{reply_type_content}>{reply_to_content}</{reply_type_content}>
</external_reply>
"""

REPLY_TO_MESSAGE_IN_CHAT = """
<reply_to id="{reply_to_id}">
    {reply_to_user}
    <{reply_type_content}>{reply_to_content}</{reply_type_content}>
</reply_to>
"""

TEXT_MESSAGE_IN_CHAT = """
<message id="{message_id}">
    {from_user}
    <{content_type}>{user_message}</{content_type}>
    <date>{date}</date>
    {reply_to_message}
</message>
"""

NOTIFICATION_MESSAGE_IN_CHAT = """
<NOTIFICATION>
    <date>{date}</date>
    <text>{notification_message}</text>
</NOTIFICATION>
"""

NOT_RESPONSE_TOOL_MESSAGE = "**Tool call empty response**"
